import glob
import os
import sys
import time
#from tkinter.messagebox import NO
from unicodedata import decimal
from unittest import result
import time

try:
    sys.path.append(glob.glob('/opt/carla-simulator/PythonAPI/carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

import argparse
import logging
import random
import matplotlib.pyplot as plt
import numpy as np
import cv2
from qpsolvers import solve_qp
import math
from copy import deepcopy
from PIL import Image
# from keras.models import load_model
# from tensorflow.image import resize
# import tensorflow as tf
# import csv
# from keras.optimizers import Adam

##-------------parameters for saving plots---------------##
dX_prev = 0
dY_prev = 0
vel_prev = 0
dPsi_prev = 0
data = []
##-------------------------------------------------------##




IM_WIDTH = 128           # width size of image
IM_HEIGHT = 128          # hight size of image
delta_dist = 3           # distance to the center of CBF image, pixels with this distance will be extracted and used in CBF
count = 0                # global counter for saving data


# redundant vars
t = time.time()
cbf = np.zeros((IM_HEIGHT, IM_WIDTH))

gaussian_cbf_img = np.zeros((IM_HEIGHT, IM_WIDTH))
depth_image = depth_image2 = depth_image3 = np.zeros((IM_HEIGHT, IM_WIDTH))
processed_depth = processed_depth2 =  processed_depth3 = np.ones((IM_HEIGHT, IM_WIDTH)) * 255


mask = mask2 = mask3  = np.zeros((IM_HEIGHT, IM_WIDTH))

side_camera_angle = 0           # rotation between cameras 
fov = 30                        # field of view of cameras   

### loading the saved keras model for CBF predictions
#model = load_model('model_056580.h5')

##------------- camera calibration matrix generation---------------##
M_int = np.identity(3)
M_int[0, 2] = IM_WIDTH/ 2.0
M_int[1, 2] = IM_HEIGHT / 2.0
M_int[0, 0] = M_int[1, 1] = IM_WIDTH / (2.0 * np.tan(fov * np.pi / 360.0))
##-----------------------------------------------------------------##

def gussian_cbf(image, kernel_size_inner, kernel_size_outer, kernel_size_final_blur):

    mask_inner = ~np.uint8(image)
    #mask_inner = array_to_vehicle_mask(image)
    mask_outer = ~mask_inner
    #plt.imshow(mask_outer)


    area_inner = np.sum(mask_inner/255)
    #print(area_inner)
    #plt.imshow(mask_inner)
    kernel_size_inner = kernel_size_outer = int(0.0343* area_inner + 106.6641)
    kernel_size_final_blur = int(0.0075* area_inner + 25.2859)

    if kernel_size_inner%2 ==0:

        kernel_size_inner += 1
        kernel_size_outer += 1

    if kernel_size_final_blur%2 ==0:

        kernel_size_final_blur += 1



    mask_edge = cv2.Canny(np.uint8(image),100,200)
    ret, mask_edge = cv2.threshold(mask_edge, 127, 255, cv2.THRESH_BINARY)
    #print(np.amax(mask_edge))
    #plt.imshow(mask_edge)

    edge_index = np.where(mask_edge==255)

    blur_inner = cv2.GaussianBlur(mask_inner,(kernel_size_inner,kernel_size_inner),0)

    # new_zero_level = blur_inner[edge_index[0][0],edge_index[1][0]]
    # blur_inner = blur_inner - new_zero_level
    

    #plt.imshow(blur_inner)

    blur_outer = cv2.GaussianBlur(mask_outer,(kernel_size_outer,kernel_size_outer),0)

    # new_zero_level = blur_outer[edge_index[0][0],edge_index[1][0]]
    # blur_outer = blur_outer - new_zero_level
    #plt.imshow(blur_outer)

    img_inner = -1 * blur_inner * (mask_inner/255)
    img_outer = blur_outer * (mask_outer/255)
    
    img = img_inner + img_outer
    img_blurred = cv2.GaussianBlur(img,(kernel_size_final_blur, kernel_size_final_blur),0)
    #img_blurred = img

    #edge_index = np.where(mask_edge==255)

    edge_index = np.where(mask_edge==255)
    
    if (len(edge_index[0]) != 0):
        new_zero_level = img_blurred[edge_index[0][-1],edge_index[1][-1]]#random.choice(edge_index[0]),random.choice(edge_index[1])]
        img_blurred = img_blurred - new_zero_level

    #new_zero_level = img_blurred[edge_index[0][0],edge_index[1][0]]
    #img_blurred = img_blurred - new_zero_level
    #print(img_blurred[edge_index])
    edges_y, edges_x = np.gradient(img_blurred)

    return img_blurred, edges_x, edges_y

def predict_trained_gan_grayscale(depth):
    """""
    This function gets depth as input and outputs the predicted CBF generated by Neural Network. The CBF image returned from this function is between -50 and 50 currently.
    """""
    global model, count

    depth = np.asarray(depth)
    depth = np.uint8(depth)
    depth = cv2.resize(depth, (256,256))
    depth = np.asarray(depth)
    depth = depth.reshape((1,256,256,1))
    depth = (depth - 127.5) / 127.5
    gen_cbf = model.predict(depth, verbose = 0)
    gen_cbf = resize(gen_cbf, [IM_HEIGHT,IM_WIDTH])

    OldValue = gen_cbf
    OldMin = -1
    NewMax = 255
    NewMin = 0
    OldMax = 1
    scaled_CBF = (((OldValue - OldMin) * (NewMax - NewMin)) / (OldMax - OldMin)) + NewMin
    scaled_CBF = np.uint8(scaled_CBF)
    scaled_CBF = scaled_CBF.reshape(IM_HEIGHT,IM_WIDTH)

    gen_cbf = scaled_CBF
    gen_cbf = (gen_cbf - 127.5) / 127.5
    gen_cbf = 50 * gen_cbf
    edges_y, edges_x = np.gradient(gen_cbf)

    return gen_cbf,  edges_x, edges_y

def distance_transform(depth):

    depth = np.asarray(depth)
    depth_not = 255 - depth
    depth = np.uint8(depth)
    depth_not = np.uint8(depth_not)
    result = depth.copy()
    result = cv2.distanceTransform(result, distanceType=cv2.DIST_L2, maskSize=3, dstType=cv2.CV_8UC1)
    result_not = depth_not.copy()
    result_not = cv2.distanceTransform(result_not, distanceType=cv2.DIST_L2, maskSize=5, dstType=cv2.CV_8UC1)
    result = -result
    final = result + result_not

    
    edges_y, edges_x = np.gradient(final)

    return final, edges_x, edges_y

def apply_cbf(ego_vehicle):

    global depth_image, mask, count, processed_depth, depth_image2, mask2, processed_depth2, depth_image3, mask3, processed_depth3


    ##---------------------------create a binary mask which only obstacles are valued as their depth there----------------------------##
    ## each variable is for each camera placed in th environment

    processed_depth = np.ones((IM_HEIGHT,IM_WIDTH)) * 255
    processed_depth[np.where(mask == 255)] = depth_image[np.where(mask == 255)]
   
    processed_depth2 = np.ones((IM_HEIGHT,IM_WIDTH)) * 255
    processed_depth2[np.where(mask2 == 255)] = depth_image2[np.where(mask2 == 255)]

    processed_depth3 = np.ones((IM_HEIGHT,IM_WIDTH)) * 255
    processed_depth3[np.where(mask3 == 255)] = depth_image3[np.where(mask3 == 255)]
    ##--------------------------------------------------------------------------------------------------------------------------------##
    

    gussian, edges_x, edges_y =  distance_transform(mask)
    gussian2, edges_x2, edges_y2 =  distance_transform(mask2)
    gussian3, edges_x3, edges_y3 =  distance_transform(mask3)


    roi = int(64)

    processed_depth[np.where(processed_depth<0.0009)] = 255

    worst_processed_depth = np.min(processed_depth[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi], axis = 0)
    worst_processed_depth_locations = np.argmin(processed_depth[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi], axis = 0)
    
    #extracting worst cbf
    worst_cbfs = np.min(gussian[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi], axis = 0)
    cbf_center_indx_2d= np.unravel_index((np.argmin(gussian[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi])), [2*roi, 2*roi])

    sort_depth_loc = np.argsort(worst_processed_depth)
    my_depth = processed_depth[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_depth = my_depth[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_depth = my_depth[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_depth = my_depth[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_depth = my_depth[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_depth = my_depth[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]
    
    my_gussian = gussian[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_gussian = my_gussian[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_gussian = my_gussian[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_gussian = my_gussian[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_gussian = my_gussian[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_gussian = my_gussian[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]
    
    my_edges_x = edges_x[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_edges_x = my_edges_x[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_edges_x = my_edges_x[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_edges_x = my_edges_x[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_edges_x = my_edges_x[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_edges_x = my_edges_x[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]
    
    my_edges_y = edges_y[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_edges_y = my_edges_y[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_edges_y = my_edges_y[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_edges_y = my_edges_y[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_edges_y = my_edges_y[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_edges_y = my_edges_y[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]

    if point1_edges_x ==0 and point1_depth!=255:
        point1_edges_x = 1
    if point2_edges_x ==0 and point2_depth!=255:
        point2_edges_x = 1
    if point3_edges_x ==0 and point3_depth!=255:
        point3_edges_x = 1
    if point4_edges_x ==0 and point4_depth!=255:
        point4_edges_x = 1
    if point5_edges_x ==0 and point5_depth!=255:
        point5_edges_x = 1
##############################################
    processed_depth2[np.where(processed_depth2<0.0009)] = 255

    worst_processed_depth = np.min(processed_depth2[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi], axis = 0)
    worst_processed_depth_locations = np.argmin(processed_depth2[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi], axis = 0)
    
    #extracting worst cbf2
    worst_cbfs = np.min(gussian2[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi], axis = 0)
    cbf_center_indx_2d= np.unravel_index((np.argmin(gussian2[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi])), [2*roi, 2*roi])

    sort_depth_loc = np.argsort(worst_processed_depth)
    my_depth = processed_depth2[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_depth2 = my_depth[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_depth2 = my_depth[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_depth2 = my_depth[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_depth2 = my_depth[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_depth2 = my_depth[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]
    
    my_gussian = gussian2[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_gussian2 = my_gussian[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_gussian2 = my_gussian[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_gussian2 = my_gussian[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_gussian2 = my_gussian[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_gussian2 = my_gussian[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]
    
    my_edges_x = edges_x2[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_edges_x2 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_edges_x2 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_edges_x2 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_edges_x2 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_edges_x2 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]
    
    my_edges_y = edges_y2[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_edges_y2 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_edges_y2 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_edges_y2 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_edges_y2 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_edges_y2 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]

    if point1_edges_x2 ==0 and point1_depth2!=255:
        point1_edges_x2 = 1
    if point2_edges_x2 ==0 and point2_depth2!=255:
        point2_edges_x2 = 1
    if point3_edges_x2 ==0 and point3_depth2!=255:
        point3_edges_x2 = 1
    if point4_edges_x2 ==0 and point4_depth2!=255:
        point4_edges_x2 = 1
    if point5_edges_x2 ==0 and point5_depth2!=255:
        point5_edges_x2 = 1
        
# ########################################3
    processed_depth3[np.where(processed_depth3<0.0009)] = 255

    worst_processed_depth = np.min(processed_depth3[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi], axis = 0)
    worst_processed_depth_locations = np.argmin(processed_depth3[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi], axis = 0)
    
    #extracting worst cbf3
    worst_cbfs = np.min(gussian3[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi], axis = 0)
    cbf_center_indx_2d= np.unravel_index((np.argmin(gussian3[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi])), [2*roi, 2*roi])

    sort_depth_loc = np.argsort(worst_processed_depth)
    my_depth = processed_depth3[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_depth3 = my_depth[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_depth3 = my_depth[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_depth3 = my_depth[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_depth3 = my_depth[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_depth3 = my_depth[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]
    
    my_gussian = gussian3[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_gussian3 = my_gussian[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_gussian3 = my_gussian[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_gussian3 = my_gussian[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_gussian3 = my_gussian[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_gussian3 = my_gussian[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]
    
    my_edges_x = edges_x3[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_edges_x3 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_edges_x3 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_edges_x3 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_edges_x3 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_edges_x3 = my_edges_x[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]
    
    my_edges_y = edges_y3[int(depth_image.shape[0]/2)-roi:int(depth_image.shape[0]/2)+roi,int(depth_image.shape[1]/2)-roi:int(depth_image.shape[1]/2)+roi]
    point1_edges_y3 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[0]] ,sort_depth_loc[0]]
    point2_edges_y3 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[1]] ,sort_depth_loc[1]]
    point3_edges_y3 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[2]] ,sort_depth_loc[2]]
    point4_edges_y3 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[3]] ,sort_depth_loc[3]]
    point5_edges_y3 = my_edges_y[worst_processed_depth_locations[sort_depth_loc[4]] ,sort_depth_loc[4]]

    if point1_edges_x3 ==0 and point1_depth3!=255:
        point1_edges_x3 = 1
    if point2_edges_x3 ==0 and point2_depth3!=255:
        point2_edges_x3 = 1
    if point3_edges_x3 ==0 and point3_depth3!=255:
        point3_edges_x3 = 1
    if point4_edges_x3 ==0 and point4_depth3!=255:
        point4_edges_x3 = 1
    if point5_edges_x3 ==0 and point5_depth3!=255:
        point5_edges_x3 = 1

  
    ##--------------------------------------------inline plotting gradients to double check-------------------------------------------##
    # img = gussian
    # edges_y, edges_x = np.gradient(img)

    # dstep = 10
    # Y,X = np.mgrid[0:IM_HEIGHT:dstep, 0:IM_WIDTH:dstep]


    # fig, (ax, ax2) = plt.subplots(1,2,figsize= (24,32))
    # ax.quiver(X,Y, edges_x[0:IM_HEIGHT:dstep, 0:IM_WIDTH:dstep],-edges_y[0:IM_HEIGHT:dstep, 0:IM_WIDTH:dstep],  color='r')
    # #ax.imshow(cbf)
    # t = ax.imshow(img, cmap='viridis', vmin = np.min(img), vmax = np.max(img))
    # fig.colorbar(t, ax = ax)
    # ax2.imshow(mask)
    # plt.show()

    # img = gussian
    # edges_y, edges_x = np.gradient(img)

    # dstep = 10
    # Y,X = np.mgrid[0:IM_HEIGHT:dstep, 0:IM_WIDTH:dstep]


    # fig, ax = plt.subplots(figsize= (24,32))
    # ax.quiver(X,Y, edges_x[0:IM_HEIGHT:dstep, 0:IM_WIDTH:dstep],-edges_y[0:IM_HEIGHT:dstep, 0:IM_WIDTH:dstep],  color='r')
    # #ax.imshow(cbf)
    # t = ax.imshow(img, cmap='viridis', vmin = np.min(img), vmax = np.max(img))
    # fig.colorbar(t, ax = ax)
    # plt.show()
    ##--------------------------------------------------------------------------------------------------------------------------------##
    ##-------------------------------------------------------saving data for fine tuning-----------------------------------
    # Save the original depth image
    # cv2.imwrite(os.path.join("/home/golnaz/vcbf/thesis/finetune_data/mask", "%d.jpg" % count), mask)
    # cv2.imwrite(os.path.join("/home/golnaz/vcbf/thesis/finetune_data/distance_transform", "%d.jpg" % count), gussian)
    # count += 1 ## adding the counter as one time step passed
    # cv2.imwrite(os.path.join("/home/golnaz/vcbf/thesis/finetune_data/mask", "%d.jpg" % count), mask2)
    # cv2.imwrite(os.path.join("/home/golnaz/vcbf/thesis/finetune_data/distance_transform", "%d.jpg" % count), gussian2)
    # count += 1
    # cv2.imwrite(os.path.join("/home/golnaz/vcbf/thesis/finetune_data/mask", "%d.jpg" % count), mask3)
    # cv2.imwrite(os.path.join("/home/golnaz/vcbf/thesis/finetune_data/distance_transform", "%d.jpg" % count), gussian3)
    # count += 1
    
    ##---------------------------------------------------------------------------------------------------------------------
    Vision = [ point1_gussian,
                point1_edges_x,
                point1_edges_y,
                point1_depth,

                point2_gussian,
                point2_edges_x,
                point2_edges_y,
                point2_depth,

                point3_gussian,
                point3_edges_x,
                point3_edges_y,
                point3_depth,

                point4_gussian,
                point4_edges_x,
                point4_edges_y,
                point4_depth,

                point5_gussian,
                point5_edges_x,
                point5_edges_y,
                point5_depth,

    ]
    #Vision2 = Vision3 = Vision

    Vision2 = [ point1_gussian2,
                point1_edges_x2,
                point1_edges_y2,
                point1_depth2,

                point2_gussian2,
                point2_edges_x2,
                point2_edges_y2,
                point2_depth2,

                point3_gussian2,
                point3_edges_x2,
                point3_edges_y2,
                point3_depth2,

                point4_gussian2,
                point4_edges_x2,
                point4_edges_y2,
                point4_depth2,

                point5_gussian2,
                point5_edges_x2,
                point5_edges_y2,
                point5_depth2,

    ]

    Vision3 = [ point1_gussian3,
                point1_edges_x3,
                point1_edges_y3,
                point1_depth3,

                point2_gussian3,
                point2_edges_x3,
                point2_edges_y3,
                point2_depth3,

                point3_gussian3,
                point3_edges_x3,
                point3_edges_y3,
                point3_depth3,

                point4_gussian3,
                point4_edges_x3,
                point4_edges_y3,
                point4_depth3,

                point5_gussian3,
                point5_edges_x3,
                point5_edges_y3,
                point5_depth3,

    ]


    cbf_throttle, cbf_steer, carBrake = controller( Vision, Vision2, Vision3, ego_vehicle)
   
    ##--------------------------------------------------------------------------------------------------------------------------------##
    
    ego_vehicle.apply_control(carla.VehicleControl( throttle = cbf_throttle, steer = cbf_steer, brake = carBrake))  ## applying control command in the environment
    return True

def depth_to_array(image, camera_num = 1):

    """
    Convert an image containing CARLA encoded depth-map to a 2D array containing
    the depth value of each pixel normalized between [0.0, 1.0] and then multiplied by 1000.
    Based on camera number final depth image will be restored in it's corresponding global variable to be used later
    """

    global depth_image, depth_image2, depth_image3
    image.convert(carla.ColorConverter.Depth)
    
    array = to_bgra_array(image)
    array = array.astype(np.float32)
    # # Apply (R + G * 256 + B * 256 * 256) / (256 * 256 * 256 - 1).
    normalized_depth = np.dot(array[:, :, :3], [65536.0, 256.0, 1.0])
    normalized_depth /= 16777215.0  # (256.0 * 256.0 * 256.0 - 1.0)
    normalized_depth = 1000 * normalized_depth
   
    ### thresholding : depth values further that 20 will be removed
    normalized_depth[normalized_depth>20] = 255
    normalized_depth = np.asarray(normalized_depth)

    ### storing depth image in coressponding global variable depend on which camera is calling it
    
    if camera_num == 1:
        depth_image = normalized_depth

    elif camera_num == 2:
        depth_image2 = normalized_depth

    else:
        depth_image3 = normalized_depth
        
    
    return depth_image

def to_bgra_array(image):
    """Convert a CARLA raw image to a BGRA numpy array."""

    array = np.frombuffer(image.raw_data, dtype=np.dtype("uint8"))
    array = np.reshape(array, (image.height, image.width, 4))
    return array

def to_rgb_array(image):
    """Convert a CARLA raw image to a RGB numpy array."""
    array = to_bgra_array(image)
    # Convert BGRA to RGB.
    array = array[:, :, :3]
    array = array[:, :, ::-1]
    return array

def labels_to_array(image):
    """
    Convert an image containing CARLA semantic segmentation labels to a 2D array
    containing the label of each pixel.
    """

    return to_bgra_array(image)[:, :, 2]

def array_to_vehicle_mask(image, camera_num = 1):
    """
    Create Mask Image for Vehicle(obstacles) using CARLA semantic segmentation and being saved in it's corresponding global variable depend on camera number
    """
    global mask, mask2, mask3

    mask = np.zeros((IM_HEIGHT, IM_WIDTH))

    array = labels_to_array(image)
    result = np.zeros((array.shape[0], array.shape[1], 3))
    result[np.where((array == 14) | (array == 15)  | (array == 16))] = (255, 255, 255) ## tag 10 is for semantic segmentation of vehicles in CARLA and 4 for walkers
    result_gray = cv2.cvtColor(np.uint8(result), cv2.COLOR_BGR2GRAY)
    (thresh, blackAndWhiteImage) = cv2.threshold(result_gray, 127, 255, cv2.THRESH_BINARY)

    if camera_num == 1:

        mask = blackAndWhiteImage ## this is a binary image version of mask since for preprosessing depth this is used
        #mask_for_gaussian = result ## this is 3 channel geayscale version of mask since this is used in gaussian CBF and probably in GAN
    
    elif camera_num == 2:

        mask2 = blackAndWhiteImage ## this is a binary image version of mask since for preprosessing depth this is used
        #mask_for_gaussian2 = result ## this is 3 channel geayscale version of mask since this is used in gaussian CBF and probably in GAN
        
    else:

        mask3 = blackAndWhiteImage ## this is a binary image version of mask since for preprosessing depth this is used
        #mask_for_gaussian3 = result ## this is 3 channel geayscale version of mask since this is used in gaussian CBF and probably in GAN
    
    return result


def labels_to_cityscapes_palette(image):

    """
    Convert an image containing CARLA semantic segmentation labels to
    Cityscapes palette.
    """
    classes = {
        0: [0, 0, 0],         # None
        1: [70, 70, 70],      # Buildings
        2: [190, 40, 40],   # Fences
        3: [55, 90, 80],       # Other
        4: [220, 20, 60],     # Pedestrians
        5: [153, 153, 153],   # Poles
        6: [157, 234, 50],    # RoadLines
        7: [128, 64, 128],    # Roads
        8: [244, 35, 232],    # Sidewalks
        9: [107, 142, 35],    # Vegetation
        10: [0, 0, 142],      # Vehicles
        11: [102, 102, 156],  # Walls
        12: [220, 220, 0],     # TrafficSigns
        13: [70,130,180],       #sky
        14: [81, 0, 81],        #ground
        15: [150, 100, 100],    #bridge
        16: [230, 150, 140],    #railtrack
        17: [180, 165, 180],    #groundRail
        18: [250, 170, 30],     #trafficLight
        19: [110, 190, 160],    #static
        20: [170, 120, 50],     #dynamic
        21: [45, 60, 150],      #water
        22: [145, 170, 100]     #terrain
    }
    array = labels_to_array(image)
    result = np.zeros((array.shape[0], array.shape[1], 3))
    for key, value in classes.items():
        result[np.where(array == key)] = value
    
    #cv2.imwrite("/home/golnaz/Desktop/CBF_GAN/CBF_CARLA/dataset/1.jpg",result)
    return result


def controller(Vision, Vision2, Vision3, ego_vehicle):
    global side_camera_angle, vel_prev, dPsi_prev, t, data, side_camera_angle
    #global M_int
    

    #try:

    """
    I assumed CBF_2D is based on camera coordinate.
    Z direction is from midpoint of image to forward.
    I also assumed that the states are based on Global coordinate.
    The camera coordinate should be converted to the global coordinate. 

    Image Coordinate:
    1. Origin: center of image on the camera
    2. X: from Camera to forward
    3. Y: Left
    4. Z: Up
    """

    car_transform = ego_vehicle.get_transform()
    (Vx, Vy, Vz) = (-ego_vehicle.get_velocity().x, ego_vehicle.get_velocity().y, ego_vehicle.get_velocity().z)

    (Wx, Wy, Wz) = (-math.radians(ego_vehicle.get_angular_velocity().x), math.radians(ego_vehicle.get_angular_velocity().y), math.radians(ego_vehicle.get_angular_velocity().z))

    # Robot State in Global Coordinate
    (X, Y, Z) = (-car_transform.location.x, car_transform.location.y, car_transform.location.z)
    

    #### converting state angle from quaternion to euler angles
    (pitch, yaw, roll)= (math.radians(car_transform.rotation.pitch), math.radians(car_transform.rotation.yaw), -math.radians(car_transform.rotation.roll))

    # Converting the left-handed frame of CARLA to right-handed one
    if yaw < 0:
        yaw = yaw + np.pi
    else:
        yaw = yaw - np.pi

    yaw = -yaw

    # Changing the name of Euler angles
    thethaa = pitch
    psii = yaw
    phii = roll

    # Rotation matrix from body to the world coordinate (In this code, we don't need this matrix)
    Rrot = np.array([ 
        [math.cos(thethaa)* math.cos(psii)   ,   (-math.cos(phii) * math.sin(psii)) + (math.sin(phii) * math.sin(thethaa) * math.cos(psii))  ,   (math.sin(phii) * math.sin(psii)) + (math.cos(phii) * math.sin(thethaa)* math.cos(psii))],
        [math.cos(thethaa)*math.sin(psii)   ,   (math.cos(phii)* math.cos(psii)) + (math.sin(phii) * math.sin(thethaa) * math.sin(psii))   ,   (-math.sin(phii) * math.cos(psii)) + (math.cos(phii) * math.sin(thethaa) * math.sin(psii))],
        [-math.sin(thethaa) ,   math.sin(phii) * math.cos(thethaa),     math.cos(phii) * math.cos(thethaa)]
    ])


    ##------------- h_img, gradient of h_img, and depth for pixels of the 3 cameras---------------##
    CBF_2D = []     # h_img for camera 1
    dCBF_2D = []    # gradient of h_img for camera 1
    depth = []      # depths for the camera 1

    CBF_2D_2 = []   # h_img for camera 2
    dCBF_2D_2 = []  # gradient of h_img for camera 2
    depth_2 = []    # depths for the camera 2

    CBF_2D_3= []    # h_img for camera 3
    dCBF_2D_3 = []  # gradient of h_img for camera 3
    depth_3 = []    # depths for the camera 3


    for i in range(len(Vision)):
        if i%4 == 0:
            CBF_2D.append(float(Vision[i]))
        if i%4 == 1:
            dCBF_2D.append([float(Vision[i]), float(Vision[i+1])])
        if i%4 == 3:
            depth.append(float(Vision[i]))

    for i in range(len(Vision2)):
        if i%4 == 0:
            CBF_2D_2.append(float(Vision2[i]))
        if i%4 == 1:
            dCBF_2D_2.append([float(Vision2[i]), float(Vision2[i+1])])
        if i%4 == 3:
            depth_2.append(float(Vision2[i]))

    for i in range(len(Vision3)):
        if i%4 == 0:
            CBF_2D_3.append(float(Vision3[i]))
        if i%4 == 1:
            dCBF_2D_3.append([float(Vision3[i]), float(Vision3[i+1])])
        if i%4 == 3:
            depth_3.append(float(Vision3[i]))



    ##------------------------- hyperparameters of the controller---------------------------------##
    relaxation = 1.0 # not used
    C_alpha = 0.9#0.95 #-----   #more conservative is value of it is less. kamtar ya bishtar bepiche
    P_alpha = 1.0 #-----
    C_betha = 0.015#1.5#0.0005#0.015 
    A_betha = 0.025#2.5#0.0005#0.025 
    P_betha = 2.0 
    Kv = 1.0
    Kw = 0.1
    Kd = 1.0
    C_gamma = 1.0
    P_gamma = 1.0
    C_eta = 1.0 # not used
    P_eta = 1.0 # not used
    Vmax = +3.0
    Vmin = +0.5
    Wmax = +4.0*np.pi
    Wmin = -4.0*np.pi
    Delta_ub = +0.5
    Delta_lb = -0.5
    heading = -np.pi/2

    C_zeta = 0.015 #parameter of h_img
    ##--------------------------------------------------------------------------------------------##

    ##------------------------- CBF = h_img + h_d ------------------------------------------------##
    CBF = []
    CBF_2 = []
    CBF_3 = []

    ## note that we can drop h_img to avoid conservativeness 
    # for i in range(5):
    #     CBF.append(C_betha*(depth[i])**P_betha + A_betha*depth[i])

    # for i in range(5):
    #     CBF_2.append(C_betha*(depth_2[i])**P_betha + A_betha*depth_2[i])
    
    # for i in range(5):
    #     CBF_3.append(C_betha*(depth_3[i])**P_betha + A_betha*depth_3[i])

    
    ## Instead of the above lines, we can use the following lines where h_img is not dropped: 
    
    for i in range(5):
        CBF.append(C_zeta*CBF_2D[i] + C_betha*(depth[i])**P_betha + A_betha*depth[i])

    for i in range(5):
        CBF_2.append(C_zeta*CBF_2D_2[i] + C_betha*(depth_2[i])**P_betha + A_betha*depth_2[i])
    
    for i in range(5):
        CBF_3.append(C_zeta*CBF_2D_3[i] + C_betha*(depth_3[i])**P_betha + A_betha*depth_3[i])
    
    ##--------------------------------------------------------------------------------------------##
    
    
    ##------------------------- worst camera (minimum CBF) ---------------------------------------##

    final_depth = []
    final_CBF = []
    final_CBF_2D = []
    final_dCBF_2D = []

    min1 =(np.min(np.asarray(CBF)))
    min2 =(np.min(np.asarray(CBF_2)))
    min3 =(np.min(np.asarray(CBF_3)))

    worst_camera_indx = np.argmin(np.asarray([min1, min2, min3]))
    worst_camera_angle = 0

    if worst_camera_indx == 0:
        final_depth = depth
        final_CBF = CBF
        final_CBF_2D = CBF_2D
        final_dCBF_2D = dCBF_2D

    if worst_camera_indx == 1:
        final_depth = depth_2
        final_CBF = CBF_2
        final_CBF_2D = CBF_2D_2
        final_dCBF_2D = dCBF_2D_2
        worst_camera_angle = math.radians(-side_camera_angle)

    if worst_camera_indx == 2:
        final_depth = depth_3
        final_CBF = CBF_3
        final_CBF_2D = CBF_2D_3
        final_dCBF_2D = dCBF_2D_3
        worst_camera_angle = math.radians(side_camera_angle)



    final_dCBF = []

    for i in range(5):

        final_dCBF.append(Rrot.dot(np.array([-(C_betha*P_betha*(final_depth[i])**(P_betha-1)+A_betha), -final_dCBF_2D[i][0], -final_dCBF_2D[i][1]])))

    #print([-(C_betha*P_betha*(final_depth[i])**(P_betha-1)+A_betha), -C_zeta*final_dCBF_2D[i][0], -C_zeta*final_dCBF_2D[i][1]])
    #print((C_betha*(final_depth[np.argmin(CBF)])**(P_betha)+A_betha*final_depth[np.argmin(CBF)]))
    ##--------------------------------------------------------------------------------------------##
    
    ##------------------------------------- Optimization Parameters ------------------------------##

    ## reference of control inputs
    Vref = Vmax     # linear velocity reference
    K_Wref = 0.5    # gain for calculating the angular velocity reference using a proportional controller
    Wref = K_Wref*(yaw-(-np.pi/2))      # calculating the angular velocity reference using a proportional controller

    
    """
    optimization variables = [v, w, delta]
    minimize: 1/2*x^T*P*x + q^T*x  s.t:  G*x <= h
    """

    P = np.diag([Kv, Kw, Kd])

    q = np.array([-Kv*Vref, -Kw*Wref, 0.0])

    G = np.array([[1.0, 0, 0],[-1.0, 0, 0],[0, 1.0, 0],[0, -1.0, 0],[0, 0, 1.0],[0, 0, -1.0],\
                  [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],\
                  [0, 0, 0]])

    h = np.array([Vmax,-Vmin,Wmax,-Wmin,Delta_ub,-Delta_lb, \
                    0, 0, 0, 0, 0, \
                    0])

    ## Lyapunov function
    V = 0.5*(0)**2+0.5*(0)**2+0.5*(psii-heading)**2     # 0.5*(x-xd)^2 + 0.5*(y-yd)^2 + 0.5*(psi-psid)^2


    ## parameters for converting from camera to body coordinate
    L = 2       # length of car
    f = 0.08    # focal length
    final_depth = final_depth   # if the depth unit is not length, we need a scale factor 
    X_cam_b = L/2   # x-position of the camera in body coordinate
    Y_cam_b = 0     # y-position of the camera in body coordinate


    ## making matrices of G and h to satisfy the CBF condition

    if worst_camera_indx == 0:
        G[6][0] = -(-(C_betha*P_betha*(final_depth[0])**(P_betha-1)+A_betha))
        G[6][1] = -(C_zeta*final_dCBF_2D[0][0]*(f/final_depth[0])*(X_cam_b+final_depth[0])+(C_betha*P_betha*(final_depth[0])**(P_betha-1)+A_betha)*Y_cam_b)
        G[6][2] = 0     # No relaxation
        h[6] = C_alpha*final_CBF[0]**P_alpha

        G[7][0] = -(-(C_betha*P_betha*(final_depth[1])**(P_betha-1)+A_betha))
        G[7][1] = -(C_zeta*final_dCBF_2D[1][0]*(f/final_depth[1])*(X_cam_b+final_depth[1])+(C_betha*P_betha*(final_depth[1])**(P_betha-1)+A_betha)*Y_cam_b)
        G[7][2] = 0     # No relaxation
        h[7] = C_alpha*final_CBF[1]**P_alpha

        G[8][0] = -(-(C_betha*P_betha*(final_depth[2])**(P_betha-1)+A_betha))
        G[8][1] = -(C_zeta*final_dCBF_2D[2][0]*(f/final_depth[2])*(X_cam_b+final_depth[2])+(C_betha*P_betha*(final_depth[2])**(P_betha-1)+A_betha)*Y_cam_b)
        G[8][2] = 0     # No relaxation
        h[8] = C_alpha*final_CBF[2]**P_alpha

        G[9][0] = -(-(C_betha*P_betha*(final_depth[3])**(P_betha-1)+A_betha))
        G[9][1] = -(C_zeta*final_dCBF_2D[3][0]*(f/final_depth[3])*(X_cam_b+final_depth[3])+(C_betha*P_betha*(final_depth[3])**(P_betha-1)+A_betha)*Y_cam_b)
        G[9][2] = 0     # No relaxation
        h[9] = C_alpha*final_CBF[3]**P_alpha
        
        G[10][0] = -(-(C_betha*P_betha*(final_depth[4])**(P_betha-1)+A_betha))
        G[10][1] = -(C_zeta*final_dCBF_2D[4][0]*(f/final_depth[4])*(X_cam_b+final_depth[4])+(C_betha*P_betha*(final_depth[4])**(P_betha-1)+A_betha)*Y_cam_b)
        G[10][2] = 0    # No relaxation
        h[10] = C_alpha*final_CBF[4]**P_alpha

    if worst_camera_indx == 1:
        G[6][0] = -(C_zeta*final_dCBF_2D[0][0]*(-(f/final_depth[0])*math.sin(math.radians(side_camera_angle))) -math.cos(math.radians(side_camera_angle))*(C_betha*P_betha*(final_depth[0])**(P_betha-1)+A_betha))
        G[6][1] = -(C_zeta*final_dCBF_2D[0][0]*(f/final_depth[0])*(math.cos(math.radians(side_camera_angle))*X_cam_b+math.sin(math.radians(side_camera_angle))*Y_cam_b+final_depth[0])+(C_betha*P_betha*(final_depth[0])**(P_betha-1)+A_betha)*(-math.sin(math.radians(side_camera_angle))*X_cam_b+math.cos(math.radians(side_camera_angle))*Y_cam_b))
        G[6][2] = 0     # No relaxation
        h[6] = C_alpha*final_CBF[0]**P_alpha

        G[7][0] = -(C_zeta*final_dCBF_2D[1][0]*(-(f/final_depth[1])*math.sin(math.radians(side_camera_angle))) -math.cos(math.radians(side_camera_angle))*(C_betha*P_betha*(final_depth[1])**(P_betha-1)+A_betha))
        G[7][1] = -(C_zeta*final_dCBF_2D[1][0]*(f/final_depth[1])*(math.cos(math.radians(side_camera_angle))*X_cam_b+math.sin(math.radians(side_camera_angle))*Y_cam_b+final_depth[1])+(C_betha*P_betha*(final_depth[1])**(P_betha-1)+A_betha)*(-math.sin(math.radians(side_camera_angle))*X_cam_b+math.cos(math.radians(side_camera_angle))*Y_cam_b))
        G[7][2] = 0     # No relaxation
        h[7] = C_alpha*final_CBF[1]**P_alpha

        G[8][0] = -(C_zeta*final_dCBF_2D[2][0]*(-(f/final_depth[2])*math.sin(math.radians(side_camera_angle))) -math.cos(math.radians(side_camera_angle))*(C_betha*P_betha*(final_depth[2])**(P_betha-1)+A_betha))
        G[8][1] = -(C_zeta*final_dCBF_2D[2][0]*(f/final_depth[2])*(math.cos(math.radians(side_camera_angle))*X_cam_b+math.sin(math.radians(side_camera_angle))*Y_cam_b+final_depth[2])+(C_betha*P_betha*(final_depth[2])**(P_betha-1)+A_betha)*(-math.sin(math.radians(side_camera_angle))*X_cam_b+math.cos(math.radians(side_camera_angle))*Y_cam_b))
        G[8][2] = 0     # No relaxation
        h[8] = C_alpha*final_CBF[2]**P_alpha

        G[9][0] = -(C_zeta*final_dCBF_2D[3][0]*(-(f/final_depth[3])*math.sin(math.radians(side_camera_angle))) -math.cos(math.radians(side_camera_angle))*(C_betha*P_betha*(final_depth[3])**(P_betha-1)+A_betha))
        G[9][1] = -(C_zeta*final_dCBF_2D[3][0]*(f/final_depth[3])*(math.cos(math.radians(side_camera_angle))*X_cam_b+math.sin(math.radians(side_camera_angle))*Y_cam_b+final_depth[3])+(C_betha*P_betha*(final_depth[3])**(P_betha-1)+A_betha)*(-math.sin(math.radians(side_camera_angle))*X_cam_b+math.cos(math.radians(side_camera_angle))*Y_cam_b))
        G[9][2] = 0     # No relaxation
        h[9] = C_alpha*final_CBF[3]**P_alpha
        
        G[10][0] = -(C_zeta*final_dCBF_2D[4][0]*(-(f/final_depth[4])*math.sin(math.radians(side_camera_angle))) -math.cos(math.radians(side_camera_angle))*(C_betha*P_betha*(final_depth[4])**(P_betha-1)+A_betha))
        G[10][1] = -(C_zeta*final_dCBF_2D[4][0]*(f/final_depth[4])*(math.cos(math.radians(side_camera_angle))*X_cam_b+math.sin(math.radians(side_camera_angle))*Y_cam_b+final_depth[4])+(C_betha*P_betha*(final_depth[4])**(P_betha-1)+A_betha)*(-math.sin(math.radians(side_camera_angle))*X_cam_b+math.cos(math.radians(side_camera_angle))*Y_cam_b))
        G[10][2] = 0    # No relaxation
        h[10] = C_alpha*final_CBF[4]**P_alpha
       

    if worst_camera_indx == 2:
        G[6][0] = -(C_zeta*final_dCBF_2D[0][0]*(-(f/final_depth[0])*math.sin(math.radians(-side_camera_angle))) -math.cos(math.radians(-side_camera_angle))*(C_betha*P_betha*(final_depth[0])**(P_betha-1)+A_betha))
        G[6][1] = -(C_zeta*final_dCBF_2D[0][0]*(f/final_depth[0])*(math.cos(math.radians(-side_camera_angle))*X_cam_b+math.sin(math.radians(-side_camera_angle))*Y_cam_b+final_depth[0])+(C_betha*P_betha*(final_depth[0])**(P_betha-1)+A_betha)*(-math.sin(math.radians(-side_camera_angle))*X_cam_b+math.cos(math.radians(-side_camera_angle))*Y_cam_b))
        G[6][2] = 0     # No relaxation
        h[6] = C_alpha*final_CBF[0]**P_alpha

        G[7][0] = -(C_zeta*final_dCBF_2D[1][0]*(-(f/final_depth[1])*math.sin(math.radians(-side_camera_angle))) -math.cos(math.radians(-side_camera_angle))*(C_betha*P_betha*(final_depth[1])**(P_betha-1)+A_betha))
        G[7][1] = -(C_zeta*final_dCBF_2D[1][0]*(f/final_depth[1])*(math.cos(math.radians(-side_camera_angle))*X_cam_b+math.sin(math.radians(-side_camera_angle))*Y_cam_b+final_depth[1])+(C_betha*P_betha*(final_depth[1])**(P_betha-1)+A_betha)*(-math.sin(math.radians(-side_camera_angle))*X_cam_b+math.cos(math.radians(-side_camera_angle))*Y_cam_b))
        G[7][2] = 0     # No relaxation
        h[7] = C_alpha*final_CBF[1]**P_alpha

        G[8][0] = -(C_zeta*final_dCBF_2D[2][0]*(-(f/final_depth[2])*math.sin(math.radians(-side_camera_angle))) -math.cos(math.radians(-side_camera_angle))*(C_betha*P_betha*(final_depth[2])**(P_betha-1)+A_betha))
        G[8][1] = -(C_zeta*final_dCBF_2D[2][0]*(f/final_depth[2])*(math.cos(math.radians(-side_camera_angle))*X_cam_b+math.sin(math.radians(-side_camera_angle))*Y_cam_b+final_depth[2])+(C_betha*P_betha*(final_depth[2])**(P_betha-1)+A_betha)*(-math.sin(math.radians(-side_camera_angle))*X_cam_b+math.cos(math.radians(-side_camera_angle))*Y_cam_b))
        G[8][2] = 0     # No relaxation
        h[8] = C_alpha*final_CBF[2]**P_alpha

        G[9][0] = -(C_zeta*final_dCBF_2D[3][0]*(-(f/final_depth[3])*math.sin(math.radians(-side_camera_angle))) -math.cos(math.radians(-side_camera_angle))*(C_betha*P_betha*(final_depth[3])**(P_betha-1)+A_betha))
        G[9][1] = -(C_zeta*final_dCBF_2D[3][0]*(f/final_depth[3])*(math.cos(math.radians(-side_camera_angle))*X_cam_b+math.sin(math.radians(-side_camera_angle))*Y_cam_b+final_depth[3])+(C_betha*P_betha*(final_depth[3])**(P_betha-1)+A_betha)*(-math.sin(math.radians(-side_camera_angle))*X_cam_b+math.cos(math.radians(-side_camera_angle))*Y_cam_b))
        G[9][2] = 0     # No relaxation
        h[9] = C_alpha*final_CBF[3]**P_alpha
        
        G[10][0] = -(C_zeta*final_dCBF_2D[4][0]*(-(f/final_depth[4])*math.sin(math.radians(-side_camera_angle))) -math.cos(math.radians(-side_camera_angle))*(C_betha*P_betha*(final_depth[4])**(P_betha-1)+A_betha))
        G[10][1] = -(C_zeta*final_dCBF_2D[4][0]*(f/final_depth[4])*(math.cos(math.radians(-side_camera_angle))*X_cam_b+math.sin(math.radians(-side_camera_angle))*Y_cam_b+final_depth[4])+(C_betha*P_betha*(final_depth[4])**(P_betha-1)+A_betha)*(-math.sin(math.radians(-side_camera_angle))*X_cam_b+math.cos(math.radians(-side_camera_angle))*Y_cam_b))
        G[10][2] = 0     # No relaxation
        h[10] = C_alpha*final_CBF[4]**P_alpha
       
    

    ## making matrices of G and h to satisfy the CLF condition

    G[11][0] = 0
    G[11][1] = (psii-heading)
    G[11][2] = -1     # relaxation
    h[11] = -C_gamma*V**P_gamma


    
    # Optimization Solver
    try:
        [vel, dPsi, Delta] = solve_qp(P, q, G, h, solver='quadprog')
        #print(f"dpsi is {dPsi} and vel is {vel} and delta is {Delta}")
        #print with two decimal digits
        print(f"dpsi is {dPsi:.2f} and vel is {vel:.2f}")

    ## Error handling in case of infeasibility
    except:
        print("exception on optimization occured")
        vel, dPsi = vel_prev, dPsi_prev     # in case of infeasibility, return the previous solution
        Delta = 0


    ## save current solution as the previous values
    vel_prev = vel
    dPsi_prev = dPsi

    ##--------------------------------------------------------------------------------------------##
    

    ##------------------------------------- Low-level Controller ---------------------------------##

    ## steering [-1,+1]

    if abs(dPsi) < 1e-3:
        steer_angle = 0

    elif dPsi > 0:
        R = abs(vel/dPsi)   # radius of turning
        steer_angle = math.atan2(L, R) 

    elif dPsi < 0:
        R = abs(vel/dPsi)   # radius of turning
        steer_angle = -math.atan2(L, R) 

    steer_angle = math.degrees(steer_angle)

    steer_angle = np.clip(steer_angle, -30.0, +30.0)

    steer = np.clip(steer_angle/30.0, -1, 1)



    ## throttle & carBrake: [0,1]

    velocity = math.sqrt(Vx**2+Vy**2+Vz**2)     # real velocity
    
    vel_clip = np.clip(vel, -30, +30)

    dV = (vel_clip-velocity)
    
    Kp = 0.3    # P-gain of velocity controller

    if dV > 0:
        throttle = np.clip(Kp*dV, 0, 1)
        carBrake = 0
    elif dV < 0:
        throttle = 0
        carBrake = Kp*np.clip(abs(Kp*dV), 0, 1)
    else:
        throttle = 0
        carBrake = 0

    ##--------------------------------------------------------------------------------------------##



    ##------------------------------------- save data --------------------------------------------##
    data.append([X, Y, Z, phii, thethaa, psii, Vx, Vy, Vz, Wx, Wy, Wz, vel, dPsi, Delta, throttle, steer, carBrake, time.time()-t])

    ##-------------------------------------- return output----------------------------------------##
    return throttle, steer, carBrake

    ##--------------------------------------------------------------------------------------------##



def main():

    global side_camera_angle, fov

    argparser = argparse.ArgumentParser(
        description=__doc__)
    argparser.add_argument(
        '--host',
        metavar='H',
        default='127.0.0.1',
        help='IP of the host server (default: 127.0.0.1)')
    argparser.add_argument(
        '-p', '--port',
        metavar='P',
        default=2000,
        type=int,
        help='TCP port to listen to (default: 2000)')
    args = argparser.parse_args()

    logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.INFO)

    client = carla.Client(args.host, args.port)
    client.set_timeout(10.0)

    try:

        world = client.get_world()
        settings = world.get_settings()
        settings.fixed_delta_seconds = 0.05
        #settings.synchronous_mode = True
        world.apply_settings(settings)

        ego_vehicle = None
        ego_cam = None
        ego_col = None
        ego_lane = None
        ego_obs = None
        ego_gnss = None
        ego_imu = None
        mysensor = None
        instance_camera = None
        instance_camera2 = None
        instance_camera3 = None
        depth_camera = None
        depth_camera2 = None
        depth_camera3 = None
        obstacle = None

        # --------------
        # Spawn ego vehicle
        # --------------
        
        ego_bp = world.get_blueprint_library().find('vehicle.tesla.model3')
        ego_bp.set_attribute('role_name','ego')
        print('\nEgo role_name is set')
        ego_color = random.choice(ego_bp.get_attribute('color').recommended_values)
        ego_bp.set_attribute('color',ego_color)
        print('\nEgo color is set')

        transform = carla.Transform(carla.Location(x=-43.5, y = 110, z = 0.5), carla.Rotation(yaw=-90))
        ego_vehicle = world.spawn_actor(ego_bp, transform)

        # ---------------------adding RGB camera blueprint---------------------------------
        # rgb_camera_bp =  world.get_blueprint_library().find('sensor.camera.rgb')
        # rgb_camera_bp.set_attribute("image_size_x", str(IM_WIDTH))
        # rgb_camera_bp.set_attribute("image_size_y", str(IM_HEIGHT))
        # rgb_camera_bp.set_attribute("fov", str(fov))
        #----------------------------------------------------------------------------------

        #----------------------adding semantic segmentation blueprint----------------------
        instance_camera_bp = None
        instance_camera_bp = world.get_blueprint_library().find('sensor.camera.semantic_segmentation')
        instance_camera_bp.set_attribute("image_size_x", str(IM_WIDTH))
        instance_camera_bp.set_attribute("image_size_y", str(IM_HEIGHT))
        instance_camera_bp.set_attribute("fov", str(fov))
        #-----------------------------------------------------------------------------------

        #-------------------adding depth sensor blueprint----------------------------------
        depth_camera_bp = None
        depth_camera_bp =  world.get_blueprint_library().find('sensor.camera.depth')
        depth_camera_bp.set_attribute("image_size_x", str(IM_WIDTH))
        depth_camera_bp.set_attribute("image_size_y", str(IM_HEIGHT))
        depth_camera_bp.set_attribute("fov", str(fov))
        #-----------------------------------------------------------------------------------

        # --------------
        # adding camera sensors to the environment
        # --------------
         
        cam_location2 = carla.Location(x = 2.4, y = 0, z = 0.5)
        cam_rotation2 = carla.Rotation(yaw = 0)
        cam_transform2 = carla.Transform(cam_location2,cam_rotation2)
        instance_camera = world.try_spawn_actor( instance_camera_bp, cam_transform2, attach_to = ego_vehicle, attachment_type = carla.AttachmentType.Rigid ) 
        instance_camera.listen(lambda image: array_to_vehicle_mask(image, camera_num = 1))

        # --------------
        # adding camera sensor 2
        # --------------
                
        cam_location3 = carla.Location(x = 2.4, y = 0, z = 0.5)
        cam_rotation3 = carla.Rotation(yaw = side_camera_angle)
        cam_transform3 = carla.Transform(cam_location3,cam_rotation3)
        instance_camera2 = world.try_spawn_actor( instance_camera_bp, cam_transform3, attach_to = ego_vehicle, attachment_type = carla.AttachmentType.Rigid ) 
        instance_camera2.listen(lambda image: array_to_vehicle_mask(image, camera_num = 2))

        # --------------
        # adding camera sensor 3
        # --------------
                
        cam_location3 = carla.Location(x = 2.4, y = 0, z = 0.5)
        cam_rotation3 = carla.Rotation(yaw = -side_camera_angle)
        cam_transform3 = carla.Transform(cam_location3,cam_rotation3)
        instance_camera3 = world.try_spawn_actor( instance_camera_bp, cam_transform3, attach_to = ego_vehicle, attachment_type = carla.AttachmentType.Rigid ) 
        instance_camera3.listen(lambda image: array_to_vehicle_mask(image, camera_num = 3))

        # --------------
        # RGB adding camera sensor
        # --------------
                
        # cam_location1 = carla.Location(x = 2.4, y = 0, z = 0.5)
        # cam_rotation1 = carla.Rotation(yaw = 0)
        # cam_transform1 = carla.Transform(cam_location1,cam_rotation1)
        # rgb_camera = world.try_spawn_actor( rgb_camera_bp, cam_transform1, attach_to = ego_vehicle, attachment_type = carla.AttachmentType.Rigid ) 
        #rgb_camera.listen(lambda image: image.save_to_disk('/home/golnaz/Desktop/CBF_GAN/CBF_CARLA/pred_imgs/pred_RGB1/%d.jpg' % count))

     

        # --------------
        # adding depth sensor
        #---------------

        
        cam_location = carla.Location(x = 2.4, y = 0, z = 0.5)
        cam_rotation = carla.Rotation(0, 0,0)
        cam_transform = carla.Transform(cam_location,cam_rotation)
        depth_camera = world.try_spawn_actor( depth_camera_bp, cam_transform, attach_to = ego_vehicle, attachment_type = carla.AttachmentType.Rigid ) 
        depth_camera.listen(lambda image: depth_to_array(image, camera_num = 1))

        # --------------
        # adding depth sensor 2
        # --------------
                
        
        cam_location3 = carla.Location(x = 2.4, y = 0, z = 0.5)
        cam_rotation3 = carla.Rotation(yaw = side_camera_angle)
        cam_transform3 = carla.Transform(cam_location3,cam_rotation3)
        depth_camera2 = world.try_spawn_actor( depth_camera_bp, cam_transform3, attach_to = ego_vehicle, attachment_type = carla.AttachmentType.Rigid ) 
        depth_camera2.listen(lambda image: depth_to_array(image, camera_num = 2))

        # --------------
        # adding depth sensor 3
        # --------------
                
        cam_location3 = carla.Location(x = 2.4, y = 0, z = 0.5)
        cam_rotation3 = carla.Rotation(yaw = -side_camera_angle)
        cam_transform3 = carla.Transform(cam_location3,cam_rotation3)
        depth_camera3 = world.try_spawn_actor( depth_camera_bp, cam_transform3, attach_to = ego_vehicle, attachment_type = carla.AttachmentType.Rigid ) 
        depth_camera3.listen(lambda image: depth_to_array(image, camera_num = 3))



        # --------------
        # adding random vehicles in the environment to challnge
        #---------------
        # actor_list = []
        #npc = []
        

        #Spawn vehicles in an 80m vicinity of the camera
        # vehicle_bp_library = world.get_blueprint_library().filter('*vehicle*')
        # radius = 80
        
        # for spawn_point in spawn_points:
            
        #     vec = [spawn_point.location.x - cam_location.x, spawn_point.location.y - cam_location.y]
        #     if vec[0]*vec[0] + vec[1]*vec[1] < radius*radius:
        #         npc =  world.try_spawn_actor(random.choice(vehicle_bp_library), spawn_point)
        #         if npc is not None:
        #             actor_list.append(npc)
        #             npc.set_autopilot(True)


        #-------------
        # spawn specific cars for our static scenario
        #-------------

        vehicle_bp_library = world.get_blueprint_library().find('vehicle.ford.ambulance')
        spawn_point = carla.Transform(carla.Location(x=-41 ,y = 94, z = 0.5), carla.Rotation(yaw=-90))
        obstacle = world.try_spawn_actor((vehicle_bp_library), spawn_point)

        vehicle_bp_library = world.get_blueprint_library().find('vehicle.carlamotors.carlacola')
        spawn_point = carla.Transform(carla.Location(x=-44.5, y = 70, z = 0.5), carla.Rotation(yaw=-90))
        obstacle1 = world.try_spawn_actor((vehicle_bp_library), spawn_point)

        vehicle_bp_library = world.get_blueprint_library().find('vehicle.dodge.charger_police_2020')
        spawn_point = carla.Transform(carla.Location(x=-38, y = 63, z = 0.5), carla.Rotation(yaw=30+180))
        obstacle2 = world.try_spawn_actor((vehicle_bp_library), spawn_point)

        vehicle_bp_library = world.get_blueprint_library().find('vehicle.volkswagen.t2')
        spawn_point = carla.Transform(carla.Location(x=-37.5, y = 73.5, z = 0.5), carla.Rotation(yaw=-45))
        obstacle4 = world.try_spawn_actor((vehicle_bp_library), spawn_point)

        vehicle_bp_library = world.get_blueprint_library().find('vehicle.mercedes.sprinter')
        spawn_point = carla.Transform(carla.Location(x=-45, y = 81, z = 0.5), carla.Rotation(yaw=-90))
        obstacle5 = world.try_spawn_actor((vehicle_bp_library), spawn_point)

        vehicle_bp_library = world.get_blueprint_library().find('vehicle.carlamotors.firetruck')
        spawn_point = carla.Transform(carla.Location(x=-48.5, y = 86, z = 0.5), carla.Rotation(yaw=90))
        obstacle6 = world.try_spawn_actor((vehicle_bp_library), spawn_point)

        vehicle_bp_library = world.get_blueprint_library().find('vehicle.tesla.cybertruck')
        spawn_point = carla.Transform(carla.Location(x=-40.25, y = 55, z = 0.5), carla.Rotation(yaw=-90))
        obstacle7 = world.try_spawn_actor((vehicle_bp_library), spawn_point)

        vehicle_bp_library = world.get_blueprint_library().find('vehicle.nissan.patrol')
        spawn_point = carla.Transform(carla.Location(x=-48.5, y = 60, z = 0.5), carla.Rotation(yaw=90))
        obstacle8 = world.try_spawn_actor((vehicle_bp_library), spawn_point)

        # --------------
        # Game loop. Prevents the script from finishing.
        # --------------
        while True:
            
            world_snapshot = world.wait_for_tick()
            apply_cbf(ego_vehicle)

            # writing data gathered at each time iteration in  a csv file
            # with open('paper_data.csv', 'a', newline='') as f_object:  
            #     # Pass the CSV  file object to the writer() function
            #     writer_object = csv.writer(f_object)
            #     # Result - a writer object
            #     # Pass the data in the list as an argument into the writerow() function
            #     writer_object.writerow(data[-1])  
            #     # Close the file object
            #     f_object.close()

        #time.sleep(5)

    finally:
        # --------------
        # Stop recording and destroy actors
        # --------------
        #client.apply_batch([carla.command.DestroyActor(x) for x in actor_list])
        #client.stop_recorder()
        if ego_vehicle is not None:
            if ego_cam is not None:

                ego_cam.stop()
                ego_cam.destroy()
            
            if instance_camera is not None:

                instance_camera.stop()
                instance_camera.destroy()

            if instance_camera2 is not None:

                instance_camera2.stop()
                instance_camera2.destroy()

            if instance_camera3 is not None:

                instance_camera3.stop()
                instance_camera3.destroy()

            # if rgb_camera is not None:

            #     rgb_camera.stop()
            #     rgb_camera.destroy()

            if ego_col is not None:

                ego_col.stop()
                ego_col.destroy()

            if ego_lane is not None:

                ego_lane.stop()
                ego_lane.destroy()

            if ego_obs is not None:

                ego_obs.stop()
                ego_obs.destroy()

            if ego_gnss is not None:

                ego_gnss.stop()
                ego_gnss.destroy()

            if ego_imu is not None:

                ego_imu.stop()
                ego_imu.destroy()

            if mysensor is not None:

                mysensor.stop()
                mysensor.destroy()

            if depth_camera is not None:
                depth_camera.stop()
                depth_camera.destroy()

            if depth_camera2 is not None:

                depth_camera2.stop()
                depth_camera2.destroy()

            if depth_camera3 is not None:

                depth_camera3.stop()
                depth_camera3.destroy()

            ego_vehicle.destroy()

        if obstacle is not None:
            obstacle.destroy()
        
        if obstacle1 is not None:
            obstacle1.destroy()
        
        if obstacle2 is not None:
            obstacle2.destroy()

        # # if obstacle3 is not None:
        # #     obstacle3.destroy()
        if obstacle4 is not None:
            obstacle4.destroy()

        if obstacle5 is not None:
            obstacle5.destroy()

        if obstacle6 is not None:
            obstacle6.destroy()

        if obstacle7 is not None:
            obstacle7.destroy()

        if obstacle8 is not None:
            obstacle8.destroy()

        print("this is finished")

if __name__ == '__main__':

    try:
        main()
        
    except KeyboardInterrupt:
        pass
    finally:
        
        print('\nDone with tutorial_ego.')